### ISSUE TITLE
Re-Deploying a cluster fails to re-install manifest CRDs onto the target

### ISSUE THREAD

**Issue by DavidFair** [stackhpc/capi-helm-charts#258]
Whilst testing different versions of Kubernetes I've run into the CRDs for Calico failing to re-install when a cluster is deleted and recreated:

- Helm install a cluster with a given name, e.g. `foo`, but leave the control plane on the bootstrap cluster
- Uninstall the cluster 
- Helm install a new cluster with the same name

This will result in a single KCP node and your worker nodes waiting for the CNI to deploy.
Looking at the manifest gives you the following:

```
  Release Name:      cni-calico-monitoring
  Target Namespace:  tigera-operator
Status:
  Phase:  Installing
Events:
  Type   Reason   Age    From  Message
  ----   ------   ----   ----  -------
  Error  Logging  4m55s  kopf  Handler 'handle_addon_updated' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 276, in execute_handler_once
    result = await invoke_handler(
  File "/venv/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 371, in invoke_handler
    result = await invocation.invoke(
  File "/venv/lib/python3.10/site-packages/kopf/_core/actions/invocation.py", line 116, in invoke
    result = await f...tches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first, resource mapping not found for name: "calico-node-metrics" namespace: "calico-system" from "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first, resource mapping not found for name: "calico-typha-metrics" namespace: "calico-system" from "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first]
  Error  Logging  3m54s  kopf  Handler 'handle_addon_updated' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 276, in execute_handler_once
    result = await invoke_handler(
  File "/venv/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 371, in invoke_handler
    result = await invocation.invoke(
  File "/venv/lib/python3.10/site-packages/kopf/_core/actions/invocation.py", line 116, in invoke
    result = await f...tches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first, resource mapping not found for name: "calico-node-metrics" namespace: "calico-system" from "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first, resource mapping not found for name: "calico-typha-metrics" namespace: "calico-system" from "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first]
  Error  Logging  2m53s  kopf  Handler 'handle_addon_updated' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 276, in execute_handler_once
    result = await invoke_handler(
  File "/venv/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 371, in invoke_handler
    result = await invocation.invoke(
  File "/venv/lib/python3.10/site-packages/kopf/_core/actions/invocation.py", line 116, in invoke
    result = await f...tches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first, resource mapping not found for name: "calico-node-metrics" namespace: "calico-system" from "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first, resource mapping not found for name: "calico-typha-metrics" namespace: "calico-system" from "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first]
  Error  Logging  113s  kopf  Handler 'handle_addon_updated' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 276, in execute_handler_once
    result = await invoke_handler(
  File "/venv/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 371, in invoke_handler
    result = await invocation.invoke(
  File "/venv/lib/python3.10/site-packages/kopf/_core/actions/invocation.py", line 116, in invoke
    result = await f...tches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first, resource mapping not found for name: "calico-node-metrics" namespace: "calico-system" from "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first, resource mapping not found for name: "calico-typha-metrics" namespace: "calico-system" from "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first]
  Error  Logging  52s  kopf  Handler 'handle_addon_updated' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 276, in execute_handler_once
    result = await invoke_handler(
  File "/venv/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 371, in invoke_handler
    result = await invocation.invoke(
  File "/venv/lib/python3.10/site-packages/kopf/_core/actions/invocation.py", line 116, in invoke
    result = await f...tches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first, resource mapping not found for name: "calico-node-metrics" namespace: "calico-system" from "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first, resource mapping not found for name: "calico-typha-metrics" namespace: "calico-system" from "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first]
```

It looks like the manifest doesn't force helm to reinstall CRDs onto the target from the bootstrap cluster once it's been installed.

I suspect there are other add-ons which use CRDs which could be impacted by this too, especially if you have development clusters which get spun up and down often.

**Comment by mkjpryor** [comment]
@DavidFair 

This is an odd one. I re-install clusters with the same name all the time for development.

I wonder whether all the `HelmRelease`s for the old cluster are deleted before you create the new one? If they are not, that would result in the new cluster picking up a deleted `HelmRelease`...

**Comment by DavidFair** [comment]
I've not seen this again since, so I'm going to close it as something environment related
