### ISSUE TITLE
Kube-Prometheus-Stack Alertmanager templateing being treated as jinja2 

### ISSUE THREAD

**Issue by anish-mudaraddi** [stackhpc/capi-helm-charts#304]
I'm working on adding some alertmanager configuration to the kube-prometheus-stack addon and I'm getting a strange issue. 

When trying to deploy config with go templates defined, the helmrelease gets stuck in pending, giving the following error:
```
Error  Logging  22s  kopf  Handler 'handle_addon_updated' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 276, in execute_handler_once
    result = await invoke_handler(
  File "/venv/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 371, in invoke_handler
    result = await invocation.invoke(
  File "/venv/lib/python3.10/site-packages/kopf/_core/actions/invocation.py", line 116, in invoke
    result = await f...thon3.10/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/venv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/venv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 49, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '.'
```

Here's an example of the values I'm changing

```
addons:
  monitoring:
    enabled: true
    lokiStack:
      enabled: false
    kubePrometheusStack:
      release:
        values:
          alertmanager:
            enabled: true

            config:
              receivers:
              - name: default-receiver
                email_configs:
                - to: <email-address>
                  send_resolved: true
                  headers:
                    subject: "({{ .CommonLabels.env }} : {{ .CommonLabels.cluster }}) {{ .Status | toUpper }} {{ .CommonLabels.alertname }}"
                  html: |-
                    <h3>You have the following alerts:</h3>
                    {{ range .Alerts }}
                    <p><b>{{.Labels.alertname}}</b>
                      <ul>{{ range .Annotations.SortedPairs }}
                      <li>{{ .Name }} = {{ .Value }}</li>
                      {{ end }}</ul>
                      <ul>{{ range .Labels.SortedPairs }}
                      <li>{{ .Name }} = {{ .Value }}</li>
                      {{ end }}</ul>
                      {{ .GeneratorURL }}</p>
                    {{ end }}

                  text: |-
                    You have the following alerts:
                    {{ range .Alerts }}
                    * {{.Labels.alertname}}
                      {{ range .Annotations.SortedPairs }}
                      {{ .Name }} = {{ .Value }}
                      {{ end }}
                      {{ range .Labels.SortedPairs }}
                      {{ .Name }} = {{ .Value }}
                      {{ end }}
                      {{ .GeneratorURL }}
                    {{ end }}

```
If I remove the go templates it seems to work fine 
I don't think this is intended?

**Comment by anish-mudaraddi** [comment]
I fixed this by enclosing the go templates with `{% raw %}` and `{% endraw %}` tags
thanks @mkjpryor for the help!
